   # {TESTING OF NUMPY}

In [1]:
import numpy as np
a = np.array ([1,2,3,4,5,6,7])
print (a)

p = np.arange(101)
p


[1 2 3 4 5 6 7]


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [2]:
k = range(1000) 
%timeit [i**2 for i in k]

71.9 µs ± 2.46 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [3]:
a = np.arange(1000)
%timeit a**2

1.61 µs ± 85.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [4]:
# creating 1-d array
b = np.array ([0,1,2,3])
b

array([0, 1, 2, 3])

In [5]:
# dimensition of array
b.ndim

1

In [6]:
# find the shape of array
b.shape

(4,)

In [7]:
# find len of array
len(b)

4

In [8]:
# creating 2-d array
c = np.array([[1,2,3,4],
      [5,6,7,8]])
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
# finding shape of array
c.shape

(2, 4)

In [10]:
len(c)

2

In [11]:
c.ndim

2

In [12]:
len(c) #returns the size of first dimension

2

In [13]:
# creating 3-d array
d = np.array ([[[0,1],[2,3]],[[4,5],[5,6]]])
d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [5, 6]]])

In [14]:
d.ndim

3

In [15]:
d.shape

(2, 2, 2)

In [16]:
len(d) #ye sirf first dimension ki hi lenth leta hai


2

# #function for creating array

In [17]:
#using arrange function
e = np.arange(0,11)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
# if we have a gap
e = np.arange(0,11,2)
e

array([ 0,  2,  4,  6,  8, 10])

In [19]:
# using linespace function
f= np.linspace(0,45,10)# (start,end,number of points)
f

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [20]:
# common arrays
g = np.ones([5, 12])
g

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [21]:
h = np.zeros ([5,5])
h

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
# identity matrix
i = np.eye(4,4)
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
# creating digonal(diag)matrix
j = np.diag([0,1,2,3,4])
j

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [24]:
# extract values
np.diag(j)

array([0, 1, 2, 3, 4])

In [25]:
j.ndim

2

In [26]:
len(j)

5

In [27]:
j.shape

(5, 5)

In [28]:
# creat array using rand0m (random value matrix)
np.random.rand(5)

array([0.15012388, 0.25649503, 0.32722756, 0.2414541 , 0.97329274])

# #Basic data typs

In [29]:
# check datatype
k = np.arange(10)

k.dtype

dtype('int32')

In [30]:
# change datatype
k = np.arange(10,dtype= "float64")
k

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [31]:
l = np.zeros([4,4])
print(l)
l.dtype

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


dtype('float64')

In [32]:
# complax datatypes
m = np.array([1+2j,2+4j])
print (m)
m.dtype

[1.+2.j 2.+4.j]


dtype('complex128')

In [33]:
# boolian datatype
n = np.array([True,False,False,True])
print (n)
n.dtype

[ True False False  True]


dtype('bool')

# #Indexing and slysing

In [34]:
o= np.arange (11)
print(o[6])

6


In [35]:
p = np.diag([1,2,3])
print (p)
print (p[2,2])

[[1 0 0]
 [0 2 0]
 [0 0 3]]
3


In [36]:
# if we have to exchage any letter on our matrix
p[1,2]=32
p

array([[ 1,  0,  0],
       [ 0,  2, 32],
       [ 0,  0,  3]])

In [37]:
q = np.arange(12)
q

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
a[1:9:2]

array([1, 3, 5, 7])

In [39]:
# if we have to reaplace multiple value at a same time 
r = np.arange (25)
r[20:]=22
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 22, 22, 22, 22, 22])

# Copies and views

In [40]:
s = np.arange (12)
print (s)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [41]:
#to copy data one array to another 
t = s[::2]# we copy s's data in t
print (t)

[ 0  2  4  6  8 10]


In [42]:
np.shares_memory(s,t)

True

In [43]:
#we can change s's value with t
t[2]= 36
print (t)

[ 0  2 36  6  8 10]


In [44]:
print (s)
# beacuse the meomary are shaired and same

[ 0  1  2  3 36  5  6  7  8  9 10 11]


In [45]:
# if we have to copy values of s into u
u = s[::2].copy()
u

array([ 0,  2, 36,  6,  8, 10])

In [46]:
np.shares_memory(s,u)

False

# fancy indexing

Using Boolean Mask

In [47]:
v= np.random.randint(0, 20,15)
v

array([ 6,  5,  8, 12,  1,  9,  6,  9, 12,  2,  1,  1,  2, 14, 10])

In [48]:
mask = (v%2 == 0)

In [49]:
extract_from_v = v [mask]
extract_from_v

array([ 6,  8, 12,  6, 12,  2,  2, 14, 10])

In [50]:
# if we have to put value of a[mask] is -1
v[mask]=-1
v

array([-1,  5, -1, -1,  1,  9, -1,  9, -1, -1,  1,  1, -1, -1, -1])

indexing with an array of intigers

In [51]:
w = np.arange (0,100,10)
w

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
# if we have to creat array with w's index
A=w[[2,3,1,2,2]]
A

array([20, 30, 10, 20, 20])

In [53]:
# if we have to new values in our array
w[[2,4]]=-200
w

array([   0,   10, -200,   30, -200,   50,   60,   70,   80,   90])

# Basic oprations 

In [54]:
# if we have to add any number in our array 
B = np.array ([1,2,3,4])
B+2

array([3, 4, 5, 6])

In [55]:
# if we have to squere of all our array
B**2

array([ 1,  4,  9, 16])

In [56]:
b= np.ones(4)+1
print(b)
print (B-b)


[2. 2. 2. 2.]
[-1.  0.  1.  2.]


In [57]:
# matrix multiplicition
C = np.diag ([1,2,3,4])
print (C*C)
print("--------------------------------------------------------")
print (C.dot (C))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
--------------------------------------------------------
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [58]:
# compairzations of arrays
D = np.array ([1,2,3,4,5,6])
E = np.array ([1,5,4,4,5,6])
D==E


array([ True, False, False,  True,  True,  True])

In [59]:
E>D

array([False,  True,  True, False, False, False])

In [60]:
# array wise compration
E= np.array ([1,2,3,4])
F= np.array ([1,2,5,4])
G= np.array ([1,2,3,4])
np.array_equal(E,F)

False

In [61]:
np.array_equal(E,G)

True

In [62]:
# logical oprations 
H = np.array([1,1,0,0],dtype=bool)
I = np.array([1,0,1,0],dtype=bool)
np.logical_or(H,I)

array([ True,  True,  True, False])

In [63]:
np.logical_and(H,I)

array([ True, False, False, False])

In [64]:
# transcendental functions
J = np.arange(5)
np.sin(J)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [65]:
np.log(J)

C:\Users\Admin\AppData\Local\Temp\ipykernel_2548\2359282054.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(J)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [66]:
np.exp(J)#evaluates e^x for each element in a given input

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [67]:
# numpy array missmatch
# K = np.arnge(4)
# L = np.array([1,2])

# Basic reduction

In [68]:
# calculating sums of array
M = np.array([1,2,3,4])
np.sum(M)

10

In [69]:
# sum by colomn and by row
N = np.array([[1,2],[3,4]])
N

array([[1, 2],
       [3, 4]])

In [70]:
N.sum(axis=0) #if axis = 0 mens colomn wise some 

array([4, 6])

In [71]:
N.sum(axis=1) #if axis = 1 mens row wise some

array([3, 7])

other reductions

In [72]:

# find minimum value
O = np.array([1,3,5,2])
O.min()

1

In [73]:
# find maxium value
O.max()

5

In [74]:
# find minium values index num
O.argmin()

0

In [75]:
# find maximum values index number
O.argmax()

2

logical Oprations

In [76]:
# if all value is true so ans is true 
np.all([True,False,True,False])

False

In [77]:
# if any value is true answer is true
np.any([True,False,True,False])

True

In [78]:
# can be used for array comparizations
P = np.zeros((50,50))
np.any(P != 0)

False

In [79]:
np.all(a==a)

True

In [80]:
AA = np.array([1,2,3,2])
BB = np.array([2,2,3,2])
CC = np.array([6,4,4,5])
((AA<=BB)&(BB<=CC)).all()

True

Statisics

In [81]:
# if we have to find mean 

Q= np.array ([1,2,3,1])
R = np.array([[1,2,3],[5,6,1]])
np.mean(Q)

1.75

In [82]:
# if we have to find median
np.median(Q)

1.5

In [83]:
# if we have to find median of 2-d array
np.median(R, axis=1)   #last axis

array([2., 5.])

In [84]:
# if we have to load text file
# data = np.loadtxt("files name.txt")
# data
# in digital daru numpy part 6 at 6.48
# please see numpy ep.6 at digital daru

# Brodcasting
please see in digital daru ep.7 of numpy

In [85]:
# if we have to creat range and repit it
S = np.tile(np.arange(0,40,10),(3,1))
print(S)
print("************************************************")

S=S.T   #.t means transverce
print (S)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
************************************************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [86]:
# if we have to add two asemetrical matrixes
T = np.array([0,1,2])
print(T)

[0 1 2]


In [87]:
S+T

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [88]:
# if we have to add new axis in our aray
T = T[:, np.newaxis]
T.shape

(3, 1)

In [89]:
# if we have to convert 2-d array to 1-d 
U =np.array([[1,2,3],[4,5,6]])
print (U)
U.ravel()

[[1 2 3]
 [4 5 6]]


array([1, 2, 3, 4, 5, 6])

In [90]:
# if we have to transpose array

U.T


array([[1, 4],
       [2, 5],
       [3, 6]])

In [91]:
U.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [92]:
# if we have to reconvert into their main shape
V = U.T.ravel()
print (V)

[1 4 2 5 3 6]


In [93]:
print (U.shape)
print (U)


(2, 3)
[[1 2 3]
 [4 5 6]]


In [94]:
W = U.ravel()
print (W)

[1 2 3 4 5 6]


In [95]:
W=W.reshape((2,3))
print(W)

[[1 2 3]
 [4 5 6]]


In [96]:
W[0,0]=5000
W

array([[5000,    2,    3],
       [   4,    5,    6]])

In [97]:
X = np.zeros((3,2))
Y = X.T.reshape((3,2))
Y[1,1]=55555

In [98]:
print (X)
print("******************************")
print(Y)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
******************************
[[    0.     0.]
 [    0. 55555.]
 [    0.     0.]]


In [99]:
# if we have to comvert 1-d array in 2-d
DD = np.array([1,2,3,4,5,6,7,8])
DD[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [100]:
EE=DD.reshape(4,2)
EE

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Resizing of matrix

In [101]:
FF = np.arange(4)
FF.resize((6,))
FF

array([0, 1, 2, 3, 0, 0])

In [102]:
# if we have to sort data
GG = np.array ([[1,5,4,6,5],[5,4,5,7,8]])
HH =np.sort(GG,axis=1)
(HH)

array([[1, 4, 5, 5, 6],
       [4, 5, 5, 7, 8]])

In [103]:
GG.sort(axis=1)
GG

array([[1, 4, 5, 5, 6],
       [4, 5, 5, 7, 8]])

In [104]:
# sorting with fancy indexing
HH = np.array([4,5,1,5,5,4,5])
print ("--------------------------------------")
JJ = np.argsort(HH)
print (JJ)

--------------------------------------
[2 0 5 1 3 4 6]


In [105]:
JJ[j]

array([[2, 2, 2, 2, 2],
       [2, 0, 2, 2, 2],
       [2, 2, 5, 2, 2],
       [2, 2, 2, 1, 2],
       [2, 2, 2, 2, 3]], dtype=int64)